version: '2'
services:
    web:
        container_name: nginx
        image: nginx:latest
        ports:
            - "8000:80"
            - "3000:443"
        restart: always
        volumes:
            - "./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./app:/var/www/app"
        volumes_from:
            - php
        depends_on:
            - php
            - mysqldb
    php:
        container_name: php
        image: nanoninja/php-fpm
        restart: always
        volumes:
            - "./configs/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./app:/var/www/app"
    composer:
        container_name: composer
        image: "composer"
        volumes:
            - "./app:/app"
        command: install
    mysqldb:
        container_name: mysql
        image: mysql:5.7
        environment:
            - MYSQL_DATABASE=chat
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        ports:
            - "8989:3306"
        volumes:
            - "./data/db:/var/lib/mysql"
            - "./data/init/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro"